### ISSUE TITLE
[Android] Dates and Calendar Personalization

### ISSUE THREAD

**Issue by nizmaylova** [openedx/openedx-app-android#103]
**Goal**

This project involves adding course data management capabilities to the new open edx mobile applications, supporting calendar syncing, personalized date shifting, and other incremental improvements to tracking dates through the mobile applications.

Slack: #wg-product-mobile
Requirement Definition: [Confluence Project Page](https://openedx.atlassian.net/wiki/spaces/OEPM/pages/3865444353/Project+-+Mobile+Dates+Calendar+Personalization)
```[tasklist]
### Tasks
- [ ] https://github.com/openedx/openedx-app-android/issues/104
- [ ] https://github.com/openedx/openedx-app-android/issues/105
- [ ] https://github.com/openedx/openedx-app-android/issues/106
- [ ] https://github.com/openedx/openedx-app-android/issues/123
- [ ] https://github.com/openedx/openedx-app-android/issues/148
- [ ] https://github.com/openedx/openedx-app-android/issues/155
- [ ] https://github.com/openedx/openedx-app-android/issues/156
- [ ] https://github.com/openedx/openedx-app-android/issues/217
- [ ] https://github.com/openedx/openedx-app-android/issues/240
```

**Comment by moiz994** [comment]
@nizmaylova can you please add this task to the task list: https://github.com/openedx/openedx-app-android/issues/148
I'm unable to update it.

**Comment by moiz994** [comment]
Still an Marco :/

Here are some more tickets that linking to this epic:
https://github.com/openedx/openedx-app-android/issues/155
https://github.com/openedx/openedx-app-android/issues/156

**Comment by nizmaylova** [comment]
@moiz994 I linked tickets to this epic

**Comment by marcotuts** [comment]
Actually sorry, I'm realizing this also tracks FC-0047 work for improved Dates & Calendar personalization. That work isn't linked to this epic I think, possibly because of this issue we have with tasklist editing access rights. 

@volodymyr-chekyrta  any tickets / PRs we could / should link to this and the iOS epics? I know the work is in review but I figured I'd check prior to closing the epic

**Comment by volodymyr-chekyrta** [comment]
@marcotuts I think we can connect this PR for android
https://github.com/openedx/openedx-app-android/pull/330
and this one for iOS
https://github.com/openedx/openedx-app-ios/pull/466
