### ISSUE TITLE
[Android] Improved Mobile Discovery

### ISSUE THREAD

**Issue by nizmaylova** [openedx/openedx-app-android#114]
**Goal**

With this effort, we’d like to shift away from the minimalist catalog discovery capabilities on Open edX mobile to match what other services support in terms of helping learners find the right course. This effort should introduce mobile friendly course and program enrollment pages and improve the ability to provide rich, valuable metadata for these pages through the core edx-platform experience (without the need for the discovery service).

Slack: #wg-product-mobile
Requirement Definition: [Confluence Project Page](https://openedx.atlassian.net/wiki/spaces/OEPM/pages/3782344705/Project+-+Improved+Mobile+Discovery+FC-28a)
```[tasklist]
### Tasks
- [ ] https://github.com/openedx/openedx-app-android/issues/115
- [ ] https://github.com/openedx/openedx-app-android/issues/116
- [ ] https://github.com/openedx/openedx-app-android/issues/117
- [ ] https://github.com/openedx/openedx-app-android/issues/128
- [ ] https://github.com/openedx/openedx-app-android/issues/129
- [ ] https://github.com/openedx/openedx-app-android/issues/130
```

**Comment by edschema** [comment]
closing: all sub-issues marked complete
