### ISSUE TITLE
[Android] Persistent Mobile Notifications / Inbox

### ISSUE THREAD

**Issue by nizmaylova** [openedx/openedx-app-android#119]
**Goal**

Supporting improved course navigation for mobile learners to support sequence based learning progressions in courses, and top level navigation cleanup as well.

Slack: #wg-product-mobile
Requirement Definition: [Confluence Project Page](https://openedx.atlassian.net/wiki/spaces/OEPM/pages/3781754886/Project+-+Mobile+Notifications+Discovery+FC-25b)
```[tasklist]
### Tasks
- [ ] https://github.com/openedx/openedx-app-android/issues/120
- [ ] https://github.com/openedx/openedx-app-android/issues/121
- [ ] https://github.com/openedx/openedx-app-android/issues/122
```

**Comment by marcotuts** [comment]
Product design / definition is completed and reflected in the confluence page.

**Comment by edschema** [comment]
Closing to move to the new wg-mobile repo; platform agnostic repo to hold epics/stories
