### ISSUE TITLE
[Android] Improved Navigation - Sequences Level

### ISSUE THREAD

**Issue by nizmaylova** [openedx/openedx-app-android#125]
```[tasklist]
### Tasks
- [ ] https://github.com/openedx/openedx-app-android/issues/126
- [ ] https://github.com/openedx/openedx-app-android/issues/164
- [ ] https://github.com/openedx/openedx-app-android/issues/195
```
