### ISSUE TITLE
[Android] Q2 2024 - Misc Bugs / Cleanup Tasks

### ISSUE THREAD

**Issue by marcotuts** [openedx/openedx-app-android#289]
```[tasklist]
### Tasks
- [ ] https://github.com/openedx/openedx-app-android/issues/138
- [ ] https://github.com/openedx/openedx-app-android/issues/139
- [ ] https://github.com/openedx/openedx-app-android/issues/186
- [ ] https://github.com/openedx/openedx-app-android/issues/198
- [ ] https://github.com/openedx/openedx-app-android/issues/199
- [ ] https://github.com/openedx/openedx-app-android/issues/200
- [ ] https://github.com/openedx/openedx-app-android/issues/165
- [ ] https://github.com/openedx/openedx-app-android/issues/153
- [ ] https://github.com/openedx/openedx-app-android/issues/205
- [ ] https://github.com/openedx/openedx-app-android/issues/206
- [ ] https://github.com/openedx/openedx-app-android/issues/207
- [ ] https://github.com/openedx/openedx-app-android/issues/209
- [ ] https://github.com/openedx/openedx-app-android/issues/210
- [ ] https://github.com/openedx/openedx-app-android/issues/231
- [ ] https://github.com/openedx/openedx-app-android/issues/232
- [ ] https://github.com/openedx/openedx-app-android/issues/131
- [ ] https://github.com/openedx/openedx-app-android/issues/238
- [ ] https://github.com/openedx/openedx-app-android/issues/193
- [ ] https://github.com/openedx/openedx-app-android/issues/141
- [ ] https://github.com/openedx/openedx-app-android/issues/329
```

**Comment by marcotuts** [comment]
Linked all open tasks (which was all of them but 1 !) to the Q3 epic. MArkign this closed.
