### ISSUE TITLE
[Android] ECommerce Capabilities

### ISSUE THREAD

**Issue by moiz994** [openedx/openedx-app-android#293]
**Epic Description:**
This epic aims to enhance the user experience of the new edX mobile app by introducing in-app payment functionality, allowing users to seamlessly upgrade their course access and access additional content through convenient in-app purchases.

**Current Implementation on legacy Apps Video Demos:** https://drive.google.com/drive/folders/1XZ7BWzlN6QjWvrmNbKCxBIfgzFMznaO8?usp=drive_link

```[tasklist]
### Tasks
- [ ] https://github.com/openedx/openedx-app-android/issues/294
- [ ] https://github.com/openedx/openedx-app-android/issues/295
- [ ] https://github.com/openedx/openedx-app-android/issues/296
- [ ] https://github.com/openedx/openedx-app-android/issues/297
- [ ] https://github.com/openedx/openedx-app-android/issues/298
- [ ] https://github.com/openedx/openedx-app-android/issues/299
- [ ] https://github.com/openedx/openedx-app-android/issues/300
- [ ] https://github.com/openedx/openedx-app-android/issues/301
- [ ] https://github.com/openedx/openedx-app-android/issues/302
- [ ] https://github.com/openedx/openedx-app-android/issues/303
- [ ] https://github.com/openedx/openedx-app-android/issues/304
- [ ] https://github.com/openedx/openedx-app-android/issues/340
```

**Comment by marcotuts** [comment]
@moiz994  - For this epic, I think it makes sense to mark this as closed, along with the child tickets potentially? For any tickets in this list that did merge upstream, we can associate them with the Open edX Commerce capabilities epic - https://github.com/openedx/openedx-app-ios/issues/427. 

For any tickets linked from this epic that should merge into the upstream repo and not into a future commerce plugin, we can also link those to 427. 

(In the future once development starts for this we can duplicate 427 sinc ethat is really only for the iOS repository, but I'm trying out only having 1 epic when projects haven't gotten to development so we have an easier to read roadmap.)

**Comment by moiz994** [comment]
Completely makes sense 👍🏼
