### ISSUE TITLE
Quick Win Feature Gaps [Mobile][Android] (FC-0028)

### ISSUE THREAD

**Issue by marcotuts** [openedx/openedx-app-android#52]
### Goal
The following project is a collection of several different items identified by the feature gap exercises completed by the mobile working group and edX mobile teams. Upon completion approximately 34% of the [gaps identified ](https://openedx.atlassian.net/wiki/spaces/OEPM/pages/3836837895)that have the smallest development scope and are quickest to complete should be delivered.

**Slack:** #wg-product-mobile
**Requirement Definition:** [Confluence Project Page](https://openedx.atlassian.net/wiki/spaces/OEPM/pages/3851780097/Project+-+Quick+Win+Feature+Gap+List)

```[tasklist]
### Tasks
- [x] Gap List Merge - edx and mobile working group
- [ ] What's New experience [Android]
- [ ] App Update messaging [Android]
- [ ] In app review system [Android]
- [ ] Transcript navigation [Android]
- [ ] Screen casting - Google Cast support [Android]
- [ ] HLS video player support and video streaming quality settings [Android]
- [ ] Landscape support [Android]
- [ ] View discussion profile [Android]
- [ ] Accessibility (Talkback support) [Android]
- [ ] JWT Auth Token support [Android]
```

**Comment by moiz994** [comment]
@marcotuts we need to add this task to this epic. 
https://github.com/openedx/openedx-app-android/issues/85

**Comment by marcotuts** [comment]
> @marcotuts we need to add this task to this epic. #85

The linked epic is part of a funded contribution with fixed scope, so I wouldn't add it to this epic. We can treat this ticket as a 1 off or if there is any set of related items we expect similar to this one we can create another quick win like epic - any suggestion on an epic label / descriptor that would wrap some of the other added items?

**Comment by moiz994** [comment]
The shared issue was mainly a bug that existed on both apps so I thought I'd create a ticket to track it as we are working to fix it. Quick wins seemed like a good fit for it but if you have another epic in mind let me know or like you said, e can keep it as a one-off.

**Comment by marcotuts** [comment]
I haven't created an epic for bug cleanups / improvements but we might want to have an epic per say quarter to capture / organize buckets of cleanup / misc tickets that are like this 'quick win' project.... I can create one and link to this ticket as a starter example. Also will look into permissions gaps related to this.
