### ISSUE TITLE
[Android] Q4 2023 - Misc Bugs / Cleanup Tasks

### ISSUE THREAD

**Issue by marcotuts** [openedx/openedx-app-android#90]
Goal:

This is a way to organize misc bugs and cleanup tasks that have otherwise no epic / home to associate them with and thus aren't represented on the roadmap.

For now we will try a quarterly ticket for iOS / Android to group these as an epic label.

```[tasklist]
### Tasks
- [ ] https://github.com/openedx/openedx-app-android/pull/84
- [ ] https://github.com/openedx/openedx-app-android/issues/85
- [ ] https://github.com/openedx/openedx-app-android/issues/147
- [ ] https://github.com/openedx/openedx-app-android/issues/152
- [ ] https://github.com/openedx/openedx-app-android/issues/173
```
```[tasklist]
### Tasks
```
