### ISSUE TITLE
[Android] Account Settings Cleanup - Support / FAQ / Email (2U)

### ISSUE THREAD

**Issue by nizmaylova** [openedx/openedx-app-android#94]
Goal

This project involves adding dedicated support page, FAQ, Email and viewing Terms of Service / Privacy Policies inside application

Slack: #wg-product-mobile
```[tasklist]
### Tasks
- [ ] https://github.com/openedx/openedx-app-android/issues/95
- [ ] https://github.com/openedx/openedx-app-android/issues/96
- [ ] https://github.com/openedx/openedx-app-android/issues/97
- [ ] https://github.com/openedx/openedx-app-android/issues/162
- [ ] https://github.com/openedx/openedx-app-android/issues/182
```
