### ISSUE TITLE
[Android] Improved Navigation - Course Home Level

### ISSUE THREAD

**Issue by nizmaylova** [openedx/openedx-app-android#98]
```[tasklist]
### Tasks
- [ ] https://github.com/openedx/openedx-app-android/issues/100
- [ ] https://github.com/openedx/openedx-app-android/issues/101
- [ ] https://github.com/openedx/openedx-app-android/issues/127
- [ ] https://github.com/openedx/openedx-app-android/issues/166
- [ ] https://github.com/openedx/openedx-app-android/issues/168
```

**Comment by marcotuts** [comment]
Marking this work closed!
